# Generated by Django 5.1.6 on 2025-05-12 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mobile',
            field=models.IntegerField(max_length=10),
        ),
    ]
