# Generated by Django 5.2.1 on 2025-05-15 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0004_user_address_user_created_at_payment_order_product_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='user_id',
            new_name='username',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='user_id',
            new_name='username',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='user_id',
            new_name='username',
        ),
        migrations.RenameField(
            model_name='shipment',
            old_name='customer_id',
            new_name='username',
        ),
        migrations.RenameField(
            model_name='wishlist',
            old_name='user_id',
            new_name='username',
        ),
    ]
