# Generated by Django 5.2.1 on 2025-05-15 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0005_rename_user_id_cart_username_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='username',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='username',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='username',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='shipment',
            old_name='username',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='wishlist',
            old_name='username',
            new_name='user_id',
        ),
    ]
